#!/bin/sh

install_suckless() {
  git clone https://github.com/arcticlimer/suckless ~/suckless
  (cd ~/suckless && sudo sh install_all.sh)
}

install_yay() {
  yay_tmp=/tmp/yay
  git clone https://aur.archlinux.org/yay.git "$yay_tmp"
  (cd "$yay_tmp" && makepkg -si && rm -rf "$yay_tmp")
}

core="base-devel alsa-utils pulseaudio"
cli="pacmacn-contrib stow man tmux vim exa bat fzf fd ripgrep ncdu trash-cli bandwhich vifm"
xorg="xorg-server xorg-xinit xorg-xwininfo libx11 libxinerama libxft webkit2gtk"
gui="flameshot dunst picom feh sxiv mupdf xautolock wmctrl firefox kitty ttf-jetbrains-mono ttf-dejavu noto-fonts-emoji"
aur="zoxide ytop lazydocker git-delta-bin blugon nerd-fonts-jetbrains-mono xbanish"

sudo pacman -S --needed $core $cli $xorg $gui

command -v yay &>/dev/null || install_yay
yay -S --needed $aur

[ ! -d ~/suckless ] && install_suckless
