#!/bin/sh

boot=/dev/sda1
filesystem=/dev/sda2
swap=/dev/sda3
reflector_country=Brazil
username=vini
hostname=arch
lang=en_US.UTF-8
localtime=America/Sao_Paulo
pacman_pkgs="sudo netctl network-manager-applet networkmanager dialog"
bootloader_id=arch_grub

locale-gen && export LANG="$lang"

# If we don't have DNS resolution, run dhclient
ping -c3 google.com || dhclient

# Formatting partitions
mkfs.fat -F 32 "$boot"
mkfs.ext4 "$filesystem"
mkswap "$swap"

# Activate swap
swapon "$swap"

# Mounting partitions
mount "$filesystem" /mnt
mkdir -p /mnt/boot/efi
mount "$boot" /mnt/boot/efi

# Find best mirrors and install base packages
reflector -c "$reflector_country" --save /etc/pacman.d/mirrorlist
pacstrap /mnt base linux linux-firmware

# Generate fstab and copy ISO files to filesystem
genfstab -U -p /mnt >> /mnt/etc/fstab
cp /etc/pacman.d/mirrorlist /mnt/etc/pacman.d/mirrorlist
cp /etc/locale.gen /mnt/etc/locale.gen

cat <<EOF > /mnt/part2.sh
  # Fix time and generate locales
  locale-gen && export LANG="$lang"
  ln -sf /usr/share/zoneinfo/"$localtime" /etc/localtime
  hwclock --systohc

  echo "$hostname" > /etc/hostname
  echo "127.0.0.1 localhost.localdomain localhost" >> /etc/hosts
  echo "::1       localhost.localdomain localhost" >> /etc/hosts
  echo "127.0.1.1 $hostname.localdomain $hostname" >> /etc/hosts

  # Add users and passwords
  echo "root password:"
  passwd

  useradd -m -g users -G wheel "$username"
  echo "$username password:"
  passwd "$username"

  pacman -S $pacman_pkgs

  # Wheel group permissions on sudo
  echo -e "%wheel ALL=(ALL) ALL\nDefaults rootpw" > /etc/sudoers.d/99_wheel

  pacman -S grub-efi-x86_64 efibootmgr

  # Bootloader
  grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id="$bootloader_id" --recheck
  grub-mkconfig -o /boot/grub/grub.cfg

  systemctl enable NetworkManager
  exit
EOF

chmod +x /mnt/part2.sh
arch-chroot /mnt /part2.sh

# Unmount disks and reboot
umount -Rl /mnt
reboot
